convert ./text/graphics/crackingSLS_qperm/wallsSetgetMaxSteelStressDir1.jpg ./text/graphics/crackingSLS_qperm/wallsSetgetMaxSteelStressDir1.eps
convert ./text/graphics/crackingSLS_qperm/wallsSetgetMaxSteelStressDir2.jpg ./text/graphics/crackingSLS_qperm/wallsSetgetMaxSteelStressDir2.eps
convert ./text/graphics/crackingSLS_qperm/deckSetgetMaxSteelStressDir1.jpg ./text/graphics/crackingSLS_qperm/deckSetgetMaxSteelStressDir1.eps
convert ./text/graphics/crackingSLS_qperm/deckSetgetMaxSteelStressDir2.jpg ./text/graphics/crackingSLS_qperm/deckSetgetMaxSteelStressDir2.eps
convert ./text/graphics/crackingSLS_qperm/foundationSetgetMaxSteelStressDir2.jpg ./text/graphics/crackingSLS_qperm/foundationSetgetMaxSteelStressDir2.eps
convert ./text/graphics/crackingSLS_qperm/foundationSetgetMaxSteelStressDir1.jpg ./text/graphics/crackingSLS_qperm/foundationSetgetMaxSteelStressDir1.eps
convert ./text/graphics/fatigueStrsULS/deckSetgetAbsSteelStressIncrementDir2.jpg ./text/graphics/fatigueStrsULS/deckSetgetAbsSteelStressIncrementDir2.eps
convert ./text/graphics/fatigueStrsULS/deckSetconcreteShearCFDir1.jpg ./text/graphics/fatigueStrsULS/deckSetconcreteShearCFDir1.eps
convert ./text/graphics/fatigueStrsULS/deckSetgetAbsSteelStressIncrementDir1.jpg ./text/graphics/fatigueStrsULS/deckSetgetAbsSteelStressIncrementDir1.eps
convert ./text/graphics/fatigueStrsULS/deckSetconcreteBendingCFDir2.jpg ./text/graphics/fatigueStrsULS/deckSetconcreteBendingCFDir2.eps
convert ./text/graphics/fatigueStrsULS/deckSetconcreteShearCFDir2.jpg ./text/graphics/fatigueStrsULS/deckSetconcreteShearCFDir2.eps
convert ./text/graphics/fatigueStrsULS/deckSetconcreteBendingCFDir1.jpg ./text/graphics/fatigueStrsULS/deckSetconcreteBendingCFDir1.eps
convert ./text/graphics/shearULS/wallsSetCFDir2.jpg ./text/graphics/shearULS/wallsSetCFDir2.eps
convert ./text/graphics/shearULS/foundationSetCFDir2.jpg ./text/graphics/shearULS/foundationSetCFDir2.eps
convert ./text/graphics/shearULS/deckSetCFDir1.jpg ./text/graphics/shearULS/deckSetCFDir1.eps
convert ./text/graphics/shearULS/wallsSetCFDir1.jpg ./text/graphics/shearULS/wallsSetCFDir1.eps
convert ./text/graphics/shearULS/deckSetCFDir2.jpg ./text/graphics/shearULS/deckSetCFDir2.eps
convert ./text/graphics/shearULS/foundationSetCFDir1.jpg ./text/graphics/shearULS/foundationSetCFDir1.eps
convert ./text/graphics/loads/GdeadLoadtotal.jpg ./text/graphics/loads/GdeadLoadtotal.eps
convert ./text/graphics/loads/QtrafSit1atotal.jpg ./text/graphics/loads/QtrafSit1atotal.eps
convert ./text/graphics/loads/QtrafSit2uniftotal.jpg ./text/graphics/loads/QtrafSit2uniftotal.eps
convert ./text/graphics/loads/GearthPresstotal.jpg ./text/graphics/loads/GearthPresstotal.eps
convert ./text/graphics/loads/QtrafSit2btotal.jpg ./text/graphics/loads/QtrafSit2btotal.eps
convert ./text/graphics/loads/QtrafSit1btotal.jpg ./text/graphics/loads/QtrafSit1btotal.eps
convert ./text/graphics/loads/QtrafSit2atotal.jpg ./text/graphics/loads/QtrafSit2atotal.eps
convert ./text/graphics/loads/GselfWeighttotal.jpg ./text/graphics/loads/GselfWeighttotal.eps
convert ./text/graphics/loads/QtrafSit1uniftotal.jpg ./text/graphics/loads/QtrafSit1uniftotal.eps
convert ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetQ1.jpg ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetQ1.eps
convert ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetM1.jpg ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetM1.eps
convert ./text/graphics/resSimplLC/GselfWeightwallsSetN1.jpg ./text/graphics/resSimplLC/GselfWeightwallsSetN1.eps
convert ./text/graphics/resSimplLC/QtrafSit1bwallsSetN2.jpg ./text/graphics/resSimplLC/QtrafSit1bwallsSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit1bwallsSetM1.jpg ./text/graphics/resSimplLC/QtrafSit1bwallsSetM1.eps
convert ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetuX.jpg ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetuX.eps
convert ./text/graphics/resSimplLC/QtrafSit1awallsSetQ1.jpg ./text/graphics/resSimplLC/QtrafSit1awallsSetQ1.eps
convert ./text/graphics/resSimplLC/GselfWeightfoundDeckSetQ1.jpg ./text/graphics/resSimplLC/GselfWeightfoundDeckSetQ1.eps
convert ./text/graphics/resSimplLC/GselfWeightfoundDeckSetQ2.jpg ./text/graphics/resSimplLC/GselfWeightfoundDeckSetQ2.eps
convert ./text/graphics/resSimplLC/GselfWeightfoundDeckSetN2.jpg ./text/graphics/resSimplLC/GselfWeightfoundDeckSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetuX.jpg ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetuX.eps
convert ./text/graphics/resSimplLC/QtrafSit1bwallsSetQ2.jpg ./text/graphics/resSimplLC/QtrafSit1bwallsSetQ2.eps
convert ./text/graphics/resSimplLC/GearthPresswallsSetQ1.jpg ./text/graphics/resSimplLC/GearthPresswallsSetQ1.eps
convert ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetuZ.jpg ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetuZ.eps
convert ./text/graphics/resSimplLC/GselfWeightwallsSetuZ.jpg ./text/graphics/resSimplLC/GselfWeightwallsSetuZ.eps
convert ./text/graphics/resSimplLC/QtrafSit1awallsSetuY.jpg ./text/graphics/resSimplLC/QtrafSit1awallsSetuY.eps
convert ./text/graphics/resSimplLC/GearthPressfoundDeckSetM1.jpg ./text/graphics/resSimplLC/GearthPressfoundDeckSetM1.eps
convert ./text/graphics/resSimplLC/GearthPressfoundDeckSetM2.jpg ./text/graphics/resSimplLC/GearthPressfoundDeckSetM2.eps
convert ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetuY.jpg ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetuY.eps
convert ./text/graphics/resSimplLC/GselfWeightwallsSetM2.jpg ./text/graphics/resSimplLC/GselfWeightwallsSetM2.eps
convert ./text/graphics/resSimplLC/GselfWeightwallsSetuX.jpg ./text/graphics/resSimplLC/GselfWeightwallsSetuX.eps
convert ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetM2.jpg ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetM2.eps
convert ./text/graphics/resSimplLC/GearthPressfoundDeckSetuX.jpg ./text/graphics/resSimplLC/GearthPressfoundDeckSetuX.eps
convert ./text/graphics/resSimplLC/QtrafSit1awallsSetN2.jpg ./text/graphics/resSimplLC/QtrafSit1awallsSetN2.eps
convert ./text/graphics/resSimplLC/GearthPressfoundDeckSetuY.jpg ./text/graphics/resSimplLC/GearthPressfoundDeckSetuY.eps
convert ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetN1.jpg ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetN1.eps
convert ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetN2.jpg ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit2bwallsSetuY.jpg ./text/graphics/resSimplLC/QtrafSit2bwallsSetuY.eps
convert ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetN1.jpg ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetN1.eps
convert ./text/graphics/resSimplLC/GselfWeightfoundDeckSetuZ.jpg ./text/graphics/resSimplLC/GselfWeightfoundDeckSetuZ.eps
convert ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetuX.jpg ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetuX.eps
convert ./text/graphics/resSimplLC/QtrafSit2awallsSetuZ.jpg ./text/graphics/resSimplLC/QtrafSit2awallsSetuZ.eps
convert ./text/graphics/resSimplLC/GearthPresswallsSetM2.jpg ./text/graphics/resSimplLC/GearthPresswallsSetM2.eps
convert ./text/graphics/resSimplLC/QtrafSit1awallsSetuX.jpg ./text/graphics/resSimplLC/QtrafSit1awallsSetuX.eps
convert ./text/graphics/resSimplLC/GselfWeightwallsSetQ1.jpg ./text/graphics/resSimplLC/GselfWeightwallsSetQ1.eps
convert ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetN2.jpg ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetN2.jpg ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetN2.eps
convert ./text/graphics/resSimplLC/GselfWeightwallsSetM1.jpg ./text/graphics/resSimplLC/GselfWeightwallsSetM1.eps
convert ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetuY.jpg ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetuY.eps
convert ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetuX.jpg ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetuX.eps
convert ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetN1.jpg ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetN1.eps
convert ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetQ1.jpg ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetQ1.eps
convert ./text/graphics/resSimplLC/QtrafSit2awallsSetQ1.jpg ./text/graphics/resSimplLC/QtrafSit2awallsSetQ1.eps
convert ./text/graphics/resSimplLC/GearthPressfoundDeckSetN1.jpg ./text/graphics/resSimplLC/GearthPressfoundDeckSetN1.eps
convert ./text/graphics/resSimplLC/QtrafSit2bwallsSetQ1.jpg ./text/graphics/resSimplLC/QtrafSit2bwallsSetQ1.eps
convert ./text/graphics/resSimplLC/QtrafSit2awallsSetuX.jpg ./text/graphics/resSimplLC/QtrafSit2awallsSetuX.eps
convert ./text/graphics/resSimplLC/GselfWeightfoundDeckSetM1.jpg ./text/graphics/resSimplLC/GselfWeightfoundDeckSetM1.eps
convert ./text/graphics/resSimplLC/GdeadLoadwallsSetQ1.jpg ./text/graphics/resSimplLC/GdeadLoadwallsSetQ1.eps
convert ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetuX.jpg ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetuX.eps
convert ./text/graphics/resSimplLC/QtrafSit2bwallsSetN2.jpg ./text/graphics/resSimplLC/QtrafSit2bwallsSetN2.eps
convert ./text/graphics/resSimplLC/GearthPresswallsSetQ2.jpg ./text/graphics/resSimplLC/GearthPresswallsSetQ2.eps
convert ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetQ2.jpg ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetQ2.eps
convert ./text/graphics/resSimplLC/QtrafSit2bwallsSetM1.jpg ./text/graphics/resSimplLC/QtrafSit2bwallsSetM1.eps
convert ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetQ1.jpg ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetQ1.eps
convert ./text/graphics/resSimplLC/QtrafSit1bwallsSetN1.jpg ./text/graphics/resSimplLC/QtrafSit1bwallsSetN1.eps
convert ./text/graphics/resSimplLC/QtrafSit1bwallsSetQ1.jpg ./text/graphics/resSimplLC/QtrafSit1bwallsSetQ1.eps
convert ./text/graphics/resSimplLC/QtrafSit1awallsSetM2.jpg ./text/graphics/resSimplLC/QtrafSit1awallsSetM2.eps
convert ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetuZ.jpg ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetuZ.eps
convert ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetuY.jpg ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetuY.eps
convert ./text/graphics/resSimplLC/QtrafSit2awallsSetM1.jpg ./text/graphics/resSimplLC/QtrafSit2awallsSetM1.eps
convert ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetM2.jpg ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetM2.eps
convert ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetQ2.jpg ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetQ2.eps
convert ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetuZ.jpg ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetuZ.eps
convert ./text/graphics/resSimplLC/QtrafSit2bwallsSetN1.jpg ./text/graphics/resSimplLC/QtrafSit2bwallsSetN1.eps
convert ./text/graphics/resSimplLC/QtrafSit2bwallsSetM2.jpg ./text/graphics/resSimplLC/QtrafSit2bwallsSetM2.eps
convert ./text/graphics/resSimplLC/GearthPresswallsSetuZ.jpg ./text/graphics/resSimplLC/GearthPresswallsSetuZ.eps
convert ./text/graphics/resSimplLC/GdeadLoadwallsSetQ2.jpg ./text/graphics/resSimplLC/GdeadLoadwallsSetQ2.eps
convert ./text/graphics/resSimplLC/GdeadLoadwallsSetuZ.jpg ./text/graphics/resSimplLC/GdeadLoadwallsSetuZ.eps
convert ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetQ2.jpg ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetQ2.eps
convert ./text/graphics/resSimplLC/GselfWeightfoundDeckSetM2.jpg ./text/graphics/resSimplLC/GselfWeightfoundDeckSetM2.eps
convert ./text/graphics/resSimplLC/QtrafSit2awallsSetM2.jpg ./text/graphics/resSimplLC/QtrafSit2awallsSetM2.eps
convert ./text/graphics/resSimplLC/QtrafSit2awallsSetN2.jpg ./text/graphics/resSimplLC/QtrafSit2awallsSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit2awallsSetQ2.jpg ./text/graphics/resSimplLC/QtrafSit2awallsSetQ2.eps
convert ./text/graphics/resSimplLC/GearthPressfoundDeckSetQ2.jpg ./text/graphics/resSimplLC/GearthPressfoundDeckSetQ2.eps
convert ./text/graphics/resSimplLC/QtrafSit1bwallsSetM2.jpg ./text/graphics/resSimplLC/QtrafSit1bwallsSetM2.eps
convert ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetQ1.jpg ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetQ1.eps
convert ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetQ2.jpg ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetQ2.eps
convert ./text/graphics/resSimplLC/GdeadLoadwallsSetuX.jpg ./text/graphics/resSimplLC/GdeadLoadwallsSetuX.eps
convert ./text/graphics/resSimplLC/QtrafSit2bwallsSetuX.jpg ./text/graphics/resSimplLC/QtrafSit2bwallsSetuX.eps
convert ./text/graphics/resSimplLC/GdeadLoadwallsSetM2.jpg ./text/graphics/resSimplLC/GdeadLoadwallsSetM2.eps
convert ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetM2.jpg ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetM2.eps
convert ./text/graphics/resSimplLC/QtrafSit2awallsSetuY.jpg ./text/graphics/resSimplLC/QtrafSit2awallsSetuY.eps
convert ./text/graphics/resSimplLC/QtrafSit1bwallsSetuY.jpg ./text/graphics/resSimplLC/QtrafSit1bwallsSetuY.eps
convert ./text/graphics/resSimplLC/GselfWeightfoundDeckSetuY.jpg ./text/graphics/resSimplLC/GselfWeightfoundDeckSetuY.eps
convert ./text/graphics/resSimplLC/QtrafSit1awallsSetN1.jpg ./text/graphics/resSimplLC/QtrafSit1awallsSetN1.eps
convert ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetQ1.jpg ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetQ1.eps
convert ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetN1.jpg ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetN1.eps
convert ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetM1.jpg ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetM1.eps
convert ./text/graphics/resSimplLC/QtrafSit1awallsSetM1.jpg ./text/graphics/resSimplLC/QtrafSit1awallsSetM1.eps
convert ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetN2.jpg ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetM1.jpg ./text/graphics/resSimplLC/QtrafSit2afoundDeckSetM1.eps
convert ./text/graphics/resSimplLC/GselfWeightwallsSetuY.jpg ./text/graphics/resSimplLC/GselfWeightwallsSetuY.eps
convert ./text/graphics/resSimplLC/GearthPresswallsSetuY.jpg ./text/graphics/resSimplLC/GearthPresswallsSetuY.eps
convert ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetuY.jpg ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetuY.eps
convert ./text/graphics/resSimplLC/QtrafSit2bwallsSetuZ.jpg ./text/graphics/resSimplLC/QtrafSit2bwallsSetuZ.eps
convert ./text/graphics/resSimplLC/QtrafSit1bwallsSetuX.jpg ./text/graphics/resSimplLC/QtrafSit1bwallsSetuX.eps
convert ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetuZ.jpg ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetuZ.eps
convert ./text/graphics/resSimplLC/GearthPressfoundDeckSetQ1.jpg ./text/graphics/resSimplLC/GearthPressfoundDeckSetQ1.eps
convert ./text/graphics/resSimplLC/GearthPresswallsSetN2.jpg ./text/graphics/resSimplLC/GearthPresswallsSetN2.eps
convert ./text/graphics/resSimplLC/GearthPresswallsSetM1.jpg ./text/graphics/resSimplLC/GearthPresswallsSetM1.eps
convert ./text/graphics/resSimplLC/QtrafSit1awallsSetuZ.jpg ./text/graphics/resSimplLC/QtrafSit1awallsSetuZ.eps
convert ./text/graphics/resSimplLC/QtrafSit1awallsSetQ2.jpg ./text/graphics/resSimplLC/QtrafSit1awallsSetQ2.eps
convert ./text/graphics/resSimplLC/GearthPresswallsSetN1.jpg ./text/graphics/resSimplLC/GearthPresswallsSetN1.eps
convert ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetM2.jpg ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetM2.eps
convert ./text/graphics/resSimplLC/GearthPressfoundDeckSetuZ.jpg ./text/graphics/resSimplLC/GearthPressfoundDeckSetuZ.eps
convert ./text/graphics/resSimplLC/GselfWeightfoundDeckSetuX.jpg ./text/graphics/resSimplLC/GselfWeightfoundDeckSetuX.eps
convert ./text/graphics/resSimplLC/GearthPressfoundDeckSetN2.jpg ./text/graphics/resSimplLC/GearthPressfoundDeckSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetuZ.jpg ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetuZ.eps
convert ./text/graphics/resSimplLC/GselfWeightwallsSetN2.jpg ./text/graphics/resSimplLC/GselfWeightwallsSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetM1.jpg ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetM1.eps
convert ./text/graphics/resSimplLC/GdeadLoadwallsSetN2.jpg ./text/graphics/resSimplLC/GdeadLoadwallsSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetuY.jpg ./text/graphics/resSimplLC/QtrafSit2bfoundDeckSetuY.eps
convert ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetM1.jpg ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetM1.eps
convert ./text/graphics/resSimplLC/QtrafSit2awallsSetN1.jpg ./text/graphics/resSimplLC/QtrafSit2awallsSetN1.eps
convert ./text/graphics/resSimplLC/GearthPresswallsSetuX.jpg ./text/graphics/resSimplLC/GearthPresswallsSetuX.eps
convert ./text/graphics/resSimplLC/GselfWeightwallsSetQ2.jpg ./text/graphics/resSimplLC/GselfWeightwallsSetQ2.eps
convert ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetQ2.jpg ./text/graphics/resSimplLC/QtrafSit1afoundDeckSetQ2.eps
convert ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetM2.jpg ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetM2.eps
convert ./text/graphics/resSimplLC/GdeadLoadwallsSetN1.jpg ./text/graphics/resSimplLC/GdeadLoadwallsSetN1.eps
convert ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetN1.jpg ./text/graphics/resSimplLC/QtrafSit1bfoundDeckSetN1.eps
convert ./text/graphics/resSimplLC/GdeadLoadwallsSetM1.jpg ./text/graphics/resSimplLC/GdeadLoadwallsSetM1.eps
convert ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetN2.jpg ./text/graphics/resSimplLC/GdeadLoadfoundDeckSetN2.eps
convert ./text/graphics/resSimplLC/QtrafSit1bwallsSetuZ.jpg ./text/graphics/resSimplLC/QtrafSit1bwallsSetuZ.eps
convert ./text/graphics/resSimplLC/QtrafSit2bwallsSetQ2.jpg ./text/graphics/resSimplLC/QtrafSit2bwallsSetQ2.eps
convert ./text/graphics/resSimplLC/GselfWeightfoundDeckSetN1.jpg ./text/graphics/resSimplLC/GselfWeightfoundDeckSetN1.eps
convert ./text/graphics/resSimplLC/GdeadLoadwallsSetuY.jpg ./text/graphics/resSimplLC/GdeadLoadwallsSetuY.eps
convert ./text/graphics/normStrsULS/wallsSetCFDir2.jpg ./text/graphics/normStrsULS/wallsSetCFDir2.eps
convert ./text/graphics/normStrsULS/foundationSetCFDir2.jpg ./text/graphics/normStrsULS/foundationSetCFDir2.eps
convert ./text/graphics/normStrsULS/deckSetCFDir1.jpg ./text/graphics/normStrsULS/deckSetCFDir1.eps
convert ./text/graphics/normStrsULS/wallsSetCFDir1.jpg ./text/graphics/normStrsULS/wallsSetCFDir1.eps
convert ./text/graphics/normStrsULS/deckSetCFDir2.jpg ./text/graphics/normStrsULS/deckSetCFDir2.eps
convert ./text/graphics/normStrsULS/foundationSetCFDir1.jpg ./text/graphics/normStrsULS/foundationSetCFDir1.eps
convert ./text/graphics/crackingSLS_freq/wallsSetgetMaxSteelStressDir1.jpg ./text/graphics/crackingSLS_freq/wallsSetgetMaxSteelStressDir1.eps
convert ./text/graphics/crackingSLS_freq/wallsSetgetMaxSteelStressDir2.jpg ./text/graphics/crackingSLS_freq/wallsSetgetMaxSteelStressDir2.eps
convert ./text/graphics/crackingSLS_freq/deckSetgetMaxSteelStressDir1.jpg ./text/graphics/crackingSLS_freq/deckSetgetMaxSteelStressDir1.eps
convert ./text/graphics/crackingSLS_freq/deckSetgetMaxSteelStressDir2.jpg ./text/graphics/crackingSLS_freq/deckSetgetMaxSteelStressDir2.eps
convert ./text/graphics/crackingSLS_freq/foundationSetgetMaxSteelStressDir2.jpg ./text/graphics/crackingSLS_freq/foundationSetgetMaxSteelStressDir2.eps
convert ./text/graphics/crackingSLS_freq/foundationSetgetMaxSteelStressDir1.jpg ./text/graphics/crackingSLS_freq/foundationSetgetMaxSteelStressDir1.eps
