# -*- coding: utf-8
\mdlr
    \sets
       {
         setDiafragmaDorsal(fillDownwards())
         setDiafragmaFrontal(fillDownwards())

         \def_set["setVoladizoIzqTramos0156"]
           {
             sel_set_cond("setVoladizoIzquierdo","hasLabel(idTramo0)")
             sel_set_cond("setVoladizoIzquierdo","hasLabel(idTramo1)")
             sel_set_cond("setVoladizoIzquierdo","hasLabel(idTramo5)")
             sel_set_cond("setVoladizoIzquierdo","hasLabel(idTramo6)")
             fillDownwards()
           }
         \def_set["setVoladizoIzqTramos24"]
           {
             sel_set_cond("setVoladizoIzquierdo","hasLabel(idTramo2)")
             sel_set_cond("setVoladizoIzquierdo","hasLabel(idTramo4)")
             fillDownwards()
           }
         \def_set["setVoladizoIzqTramo3"]
           {
             sel_set_cond("setVoladizoIzquierdo","hasLabel(idTramo3)")
             fillDownwards()
           }
         \def_set["setVoladizoDerTramos0156"]
           {
             sel_set_cond("setVoladizoDerecho","hasLabel(idTramo0)")
             sel_set_cond("setVoladizoDerecho","hasLabel(idTramo1)")
             sel_set_cond("setVoladizoDerecho","hasLabel(idTramo5)")
             sel_set_cond("setVoladizoDerecho","hasLabel(idTramo6)")
             fillDownwards()
           }
         \def_set["setVoladizoDerTramos24"]
           {
             sel_set_cond("setVoladizoDerecho","hasLabel(idTramo2)")
             sel_set_cond("setVoladizoDerecho","hasLabel(idTramo4)")
             fillDownwards()
           }
         \def_set["setVoladizoDerTramo3"]
           {
             sel_set_cond("setVoladizoDerecho","hasLabel(idTramo3)")
             fillDownwards()
           }
         \def_set["setLosaViaIzqTramos0156"]
           {
             sel_set_cond("setLosaViaIzquierda","hasLabel(idTramo0)")
             sel_set_cond("setLosaViaIzquierda","hasLabel(idTramo1)")
             sel_set_cond("setLosaViaIzquierda","hasLabel(idTramo5)")
             sel_set_cond("setLosaViaIzquierda","hasLabel(idTramo6)")
             fillDownwards()
           }
         \def_set["setLosaViaIzqTramos24"]
           {
             sel_set_cond("setLosaViaIzquierda","hasLabel(idTramo2)")
             sel_set_cond("setLosaViaIzquierda","hasLabel(idTramo4)")
             fillDownwards()
           }
         \def_set["setLosaViaIzqTramo3"]
           {
             sel_set_cond("setLosaViaIzquierda","hasLabel(idTramo3)")
             fillDownwards()
           }
         \def_set["setLosaViaDerTramos0156"]
           {
             sel_set_cond("setLosaViaDerecha","hasLabel(idTramo0)")
             sel_set_cond("setLosaViaDerecha","hasLabel(idTramo1)")
             sel_set_cond("setLosaViaDerecha","hasLabel(idTramo5)")
             sel_set_cond("setLosaViaDerecha","hasLabel(idTramo6)")
             fillDownwards()
           }
         \def_set["setLosaViaDerTramos24"]
           {
             sel_set_cond("setLosaViaDerecha","hasLabel(idTramo2)")
             sel_set_cond("setLosaViaDerecha","hasLabel(idTramo4)")
             fillDownwards()
           }
         \def_set["setLosaViaDerTramo3"]
           {
             sel_set_cond("setLosaViaDerecha","hasLabel(idTramo3)")
             fillDownwards()
           }
         \def_set["setLosaInfIzqTramos0156"]
           {
             sel_set_cond("setLosaInfIzquierda","hasLabel(idTramo0)")
             sel_set_cond("setLosaInfIzquierda","hasLabel(idTramo1)")
             sel_set_cond("setLosaInfIzquierda","hasLabel(idTramo5)")
             sel_set_cond("setLosaInfIzquierda","hasLabel(idTramo6)")
             fillDownwards()
           }
         \def_set["setLosaInfIzqTramos24"]
           {
             sel_set_cond("setLosaInfIzquierda","hasLabel(idTramo2)")
             sel_set_cond("setLosaInfIzquierda","hasLabel(idTramo4)")
             fillDownwards()
           }
         \def_set["setLosaInfIzqTramo3"]
           {
             sel_set_cond("setLosaInfIzquierda","hasLabel(idTramo3)")
             fillDownwards()
           }
         \def_set["setLosaInfDerTramos0156"]
           {
             sel_set_cond("setLosaInfDerecha","hasLabel(idTramo0)")
             sel_set_cond("setLosaInfDerecha","hasLabel(idTramo1)")
             sel_set_cond("setLosaInfDerecha","hasLabel(idTramo5)")
             sel_set_cond("setLosaInfDerecha","hasLabel(idTramo6)")
             fillDownwards()
           }
         \def_set["setLosaInfDerTramos24"]
           {
             sel_set_cond("setLosaInfDerecha","hasLabel(idTramo2)")
             sel_set_cond("setLosaInfDerecha","hasLabel(idTramo4)")
             fillDownwards()
           }
         \def_set["setLosaInfDerTramo3"]
           {
             sel_set_cond("setLosaInfDerecha","hasLabel(idTramo3)")
             fillDownwards()
           }
       }
  }
